### ISSUE TITLE
Is hash-bang necessary?

### ISSUE THREAD

**Issue by dionyziz** [bahamas10/node-autolinks#5]
The hash-bang causes problems when minifying with uglify. Please see the issue at https://github.com/mishoo/UglifyJS2/issues/793

This could easily be fixed if the hash-bang line was removed from autolinks.

**Comment by avdg** [comment]
If you feel like testing, I've pushed some code to a separate branch

See https://github.com/mishoo/UglifyJS2/issues/509#issuecomment-139828281
